name: Docker Pipeline

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  sonar:
    uses: ./.github/workflows/sonar-analysis.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build-and-push:
    needs: [build, sonar]
    uses: ./.github/workflows/docker_pipelines/build-and-push.yml
    with:
      run_number: ${{ github.run_number }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}